[package]
name = "dungeon_server"
version = "0.1.0"
authors = ["aschuhardt <aschuhardt@gmail.com>"]
build = "build.rs"

[dependencies]
rustc-serialize = "0.3"
uuid = { version = "0.2", features = ["rustc-serialize", "v4", "v5"] }
time = "0.1"
bincode = "0.6.0"
